tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "ngrok/ngrok"
brew "autojump"
brew "awscli"
brew "ccat"
brew "fzf"
brew "git"
brew "git-lfs"
brew "jq"
brew "mas"
brew "nvm"
brew "openjdk"
brew "php"
brew "redis"
brew "tmux"
brew "awscli"
brew "vim"
brew "wget"
brew "postgresql"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "dbeaver-community"
cask "docker"
cask "font-fontawesome"
cask "font-meslo-for-powerline"
cask "font-meslo-lg-nerd-font"
cask "aws-vpn-client"
cask "rectangle"
cask "google-chrome"
cask "microsoft-edge"
cask "figma"
cask "slack"
cask "alfred"
cask "notion"
cask "iterm2"
cask "lens"
cask "jetbrains-toolbox"
cask "visual-studio-code"
mas "Xcode", id: 497799835
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "카카오톡", id: 869223134
mas "Microsoft To Do", id: 1274495053
